#- type: log
#  paths:
#    - "/var/log/custom/*.log"
#  exclude_files:
#    - ".*filebeat.*"
#    - ".*kube-system.*"
#  symlinks: true
#  json.message_key: log
#  json.keys_under_root: true
#  json.add_error_key: true
#  multiline.pattern: '^\s'
#  multiline.match: after
